### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gocpp** [reu/keepup#2]
Core was generated by `keepup -d ./run1.sh'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fb4da897c14 in fork () from /lib64/libc.so.6

**Comment by gocpp** [comment]
Core was generated by `keepup -d /data/www/run1.sh'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f483069fc18 in __libc_fork () at ../nptl/sysdeps/unix/sysv/linux/fork.c:56
56  {
(gdb)
